# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('miso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
